###########################################################
###--------------------plugins--------------------------###
###########################################################

# hyprpm <- comando para  gestionar plugins


# https://github.com/hyprwm/hyprland-plugins


