###########################################################
###--------------------plugins--------------------------###
###########################################################

# hyprpm <- comando para  gestionar plugins

## https://github.com/yayuuu/hyprland-scroll-overview

plugin {
    scrolloverview {
        gesture_distance = 300 # how far is the "max" for the gesture
        scale = 0.6 # preferred overview scale
        workspace_gap = 50
        wallpaper = 2 # 0: global only, 1: per-workspace only, 2: both
        blur = true # blur only the main overview wallpaper

        shadow {
            enabled = true
            range = 50
            render_power = 3
            color = rgba(2e2e2eee)
        }
    }
}

# bind = $mainMod, o, scrolloverview:overview, toggle
bind = $mainMod, o, scrolloverview:overview, enable


