###########################################################
###########################################################
###                                                     ###
###      _   _                  _                 _     ###
###     | | | |_   _ _ __  _ __| | __ _ _ __   __| |    ###
###     | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |    ###
###     |  _  | |_| | |_) | |  | | (_| | | | | (_| |    ###
###     |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|    ###
###            |___/|_|                                 ###
###                                                     ###
########################################################### 
###------------------hyprland_config--------------------###
###########################################################


###---------------------MONITORS------------------------###

#https://wiki.hyprland.org/Configuring/Monitors/
#hyprctl monitors -> consulta lista de monitores recocido
# monitor = , preferred, auto, auto
monitor = eDP-1, 1366x768, auto, auto
# monitor = HDMI-A-2, 1920x1080, auto, auto

###-----------------WORKSPACE_MONITORS------------------###
# workspace = 1, monitor:eDP-1
# workspace = 2, monitor:HDMI-A-2
# workspace = 3, monitor:HDMI-A-2
# workspace = 4, monitor:eDP-1
# workspace = 5, monitor:HDMI-A-2
# workspace = 6, monitor:HDMI-A-2


###########################################################
###--------------------AUTOSTART------------------------###
###########################################################
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = awww-daemon &
exec-once = ~/.config/hypr/random_imagen.sh & 
exec-once = hypridle & # iniciando el control para himbernacion del sistema
exec-once = mako & # iniciando el gestor de notificaciones
exec-once = wlsunset -S 6:00 -s 19:00 -t 5500 -T 6500 -d 2 & # inicio de luz "nocturna"
exec-once = udiskie & # iniciando el montador de usb
# instalar:  yay -S xdg-desktop-portal-hyprland-git , para el soporte de compartir pantalla 

###-------------------iniciar_eww-----------------------###
exec-once = ~/.eww/target/release/eww -c ~/.config/hypr/eww/widget_inf_system daemon &
exec-once = ~/.eww/target/release/eww -c ~/.config/hypr/eww/widget_inf_system open widget_inf &


###----------------keys_and_programs--------------------###
source = ~/.config/hypr/modules/keys_and_programs.conf

###--------------windows_and_workspaces-----------------###
source = ~/.config/hypr/modules/windows_and_workspaces.conf

###-----------------colors_and_look---------------------###
source = ~/.config/hypr/modules/look.conf

###----------------------input--------------------------###
source = ~/.config/hypr/modules/input.conf


